---
vagrantfile-local:
    vm:
        box: ubuntu-precise1204-x32-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                QM4S8XS1SGAM:
                    host: '8081'
                    guest: '80'
                FHmNoXX6xURd:
                    host: '8082'
                    guest: '8000'
                B3mKisgG241d:
                    host: '8083'
                    guest: '8080'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '4096'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            KKVmULU1Ed9j:
                id: vagrant-root
                source: ./webroot
                target: /var/www/html/devweb
                nfs: 'false'
            UOEL3pe3rCdc:
                id: julia-sudoku
                source: ./julia-sudoku
                target: /home/sudoku
                nfs: 'false'
            UOELApe3rCdc:
                id: node-rest
                source: ./node-rest
                target: /home/node
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
        - curl
        - julia
        - nodejs
        - apache2-utils
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
nginx:
    install: '1'
    vhosts:
        lDLDrGvFItIR:
            server_name: dev.thebitfarm.org
            server_aliases:
                - dev.thebitfarm.org
            www_root: /var/www/html/devweb
            listen_port: '8080'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
php:
    install: '1'
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: earthd3v
    phpmyadmin: '1'
    adminer: 0
    databases:
        2u7h6oPkzvWT:
            grant:
                - ALL
            name: devdb
            host: localhost
            user: dev
            password: earthd3v
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases:
        wzHRaIdLNDIo:
            name: devdb
            user: dev
            password: earthD3v
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

